### ISSUE TITLE
BUG: Gatsby Build Issue just by Adding Netlify JS Client API

### ISSUE THREAD

**Issue by hendhyhutomo** [netlify/js-client#229] opened 2020-12-12 18:40 UTC
Yesterday after I updated my package set there is an error that occurs that causes the Gatsby Build to file.
After further investigation removing the NETLIFY js API seems to fix the issue.

The build error is as follows:
`failed Building static HTML for pages - 20.250s
error Building static HTML failed

  131 | 
  132 | const path = require('path').join(__dirname, 'elf_cam_bg.wasm');
> 133 | const bytes = require('fs').readFileSync(path);
      |                           ^
  134 | 
  135 | const wasmModule = new WebAssembly.Module(bytes);
  136 | const wasmInstance = new WebAssembly.Instance(wasmModule, imports);

  WebpackError: ENOENT: no such file or directory, open '/elf_cam_bg.wasm'`

![Screenshot 2020-12-13 at 01 34 09](https://user-images.githubusercontent.com/11151079/101992150-a9dce180-3ce3-11eb-8966-5fa7a469ca0b.png)

Tested on Netlify with Node 14.15.1
and also Locally on Mac OS with node 15.1.0 and 14.15.0

**Comment by erezrokah** [comment] 2020-12-13 13:24
Hi @hendhyhutomo, do you mind sharing a repo reproducing the issue? That would make it much easier to track down the underlying cause

**Comment by hendhyhutomo** [comment] 2020-12-13 18:21
I have made a new project here
https://gitlab.com/hendhyhutomo/herbamojo-error.git
The error will only show on the previous commit.
Netlify is used in@deploystatus.js file

**Comment by ehmicky** [comment] 2020-12-14 15:41
This looks related to the new Netlify Functions runtime detection (https://github.com/netlify/zip-it-and-ship-it/pull/226).
@calavera Do you know what the problem might be?

**Comment by mraerino** [comment] 2020-12-14 16:20
i don't really get why it would be related?
how could the changes we made be related with a missing file?

**Comment by ehmicky** [comment] 2020-12-14 16:49
The file that's missing is `elf_cam_bg.wasm`, which seems related to [`elf-cam`](https://github.com/netlify/elf-cam), which was added by this PR.

**Comment by mraerino** [comment] 2020-12-14 18:19
oh, i see. seems webpack doesn't like to bundle it. can we somehow exclude from builds targeting browsers?

**Comment by kaganjd** [comment] 2020-12-20 04:21
Linking the forum thread here: https://community.netlify.com/t/gatsby-build-fail-by-implementing-netlify-api-js-client/28208

**Comment by erezrokah** [comment] 2020-12-20 10:58
Hi @hendhyhutomo, as a workaround you can add `@netlify/zip-it-and-ship-it` to the externals list of you webpack configuration. That part of the Netlify JS Client API is not browser compatible anyway.
I've opened a MR for it:
https://gitlab.com/hendhyhutomo/herbamojo-error/-/merge_requests/2

**Comment by hendhyhutomo** [comment] 2020-12-20 17:17
Owh that works! amazing!

But we need to keep this open for the team to produce an actual fix.

**Comment by amykapernick** [comment] 2021-01-28 04:45
So I'm getting this same error on my Next Site

**Comment by apmitchell** [comment] 2021-04-01 23:53
I'm having this issue currently, and suddenly trying to build a _serverless_ project

**Comment by eduardoboucas** [comment] 2021-05-27 09:42
This should be fixed with version 7.0.0, since `@netlify/zip-it-and-ship-it` is no longer a dependency. If you're still seeing the error, please add a comment and I'll reopen the issue.

Thanks for your patience! 🙌🏻

**Closed by eduardoboucas** 2021-05-27 09:42 UTC
